biblioteca-frontend/biblioteca-frontend/Models/Catalogo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace biblioteca_frontend.Models
{
    public class Catalogo
    {
        public int id_articulo { get; set; }
        public string tx_cod_bibl { get; set; }
        public string tx_descripcion { get; set; }
        public Nullable<int> nu_estado { get; set; }
        public string tx_ubicacion1 { get; set; }
        public string tx_ubicacion2 { get; set; }
        public string tx_cod_barras { get; set; }
        public string tx_imagen_url { get; set; }
        public string tx_autor { get; set; }
        public string tx_descripcion2 { get; set; }
    }
}

biblioteca-frontend/biblioteca-frontend/Models/Login.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace biblioteca_frontend.Models
{
    public class Login
    {
        public string email { get; set; }
        public string contrasena { get; set; }
    }
}

biblioteca-frontend/biblioteca-frontend/Controllers/CatalogoController.cs
using biblioteca_frontend.Models;
using biblioteca_frontend.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace biblioteca_frontend.Controllers
{
    public class CatalogoController : Controller
    {
        private CatalogoRepository catalogoService;

        public CatalogoController()
        {
            catalogoService = new CatalogoRepository();
        }

        public ActionResult Details(int id)
        {
            Catalogo catalogo = catalogoService.GetSigle(id);
            return View(catalogo);
        }

    }
}

biblioteca-frontend/biblioteca-frontend/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using biblioteca_frontend.Repository;
using biblioteca_frontend.Models;

namespace biblioteca_frontend.Controllers
{
    public class HomeController : Controller
    {

        private CatalogoRepository catalogoService;
        private LectorRepository lectorService;
        public HomeController()
        {
            catalogoService = new CatalogoRepository();
            lectorService = new LectorRepository();
        }

        public ActionResult Index()
        {
            List<Catalogo> catalogos = catalogoService.GetAll().ToList();
            return View(catalogos);
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Login(Login user)
        {
           
            Lector lector = lectorService.Login(user);
            if (lector != null)
            {
                Session["user"] = lector;
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Message = "Email o Contraseña incorrectas.";
                return View();
            }
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(Lector lector)
        {
            try
            {
                Lector response = lectorService.Create(lector);
                return RedirectToAction("Login","Home");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult Search(string name)
        {
            List<Catalogo> catalogos = catalogoService.Search(name).ToList();
            return PartialView("_Catalogo", catalogos);
        }


        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

biblioteca-frontend/biblioteca-frontend/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

biblioteca-frontend/biblioteca-frontend/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

biblioteca-frontend/biblioteca-frontend/Views/Home/Index.cshtml
@model List<biblioteca_frontend.Models.Catalogo>
@{
    ViewBag.Title = "Home Page";
    Layout = null;
}
@*Html.Partial La vista parcial es una vista reutilizable, que se puede utilizar como vista secundaria en varias otras vistas.*@
@*Representa el contenido de la vista parcial en la vista referida. El parámetro modelo pasa el objeto modelo a la vista parcial.*@
@Html.Partial("_Catalogo", Model) 

biblioteca-frontend/biblioteca-frontend/Views/Home/Login.cshtml
@{
    ViewBag.Title = "Login";
    string message = ViewBag.Message;
}


@if (message != null)
{
    <div class="alert alert-danger">
        <div>@message</div>
    </div>
}
	  <!-- Login -->
<section class="section-padding login-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-4 mx-auto">
                <div class="card padding-card">
                    <div class="card-body">
                        <h5 class="card-title mb-4">Login</h5>
                        <form action="@Url.Action("Login","Home")" method="post">
                            <div class="form-group">
                                <label>Email<span class="text-danger">*</span></label>
                                <input type="email" class="form-control" name="email" placeholder="">
                            </div>
                            <div class="form-group">
                                <label>Contraseña <span class="text-danger">*</span></label>
                                <input type="password" class="form-control" name="contrasena" placeholder="">
                            </div>
                            <div class="form-group">


                            </div>
                            <button type="submit" class="btn btn-success btn-block">SIGN IN</button>
                        </form>
                        <div class="mt-4 text-center">
                            <a href="forget.html">Forget your password?</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Login -->

biblioteca-frontend/biblioteca-frontend/Views/Home/Register.cshtml
@{
    ViewBag.Title = "Register";
}

<!-- Register -->
<section class="section-padding register-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-md-5 mx-auto">
                <div class="card padding-card">
                    <div class="card-body">
                        <h5 class="card-title mb-4">Registro</h5>
                        <form action="@Url.Action("Register","Home")" method="post">
                            <div class="form-group">
                                <label>Nombres<span class="text-danger">*</span></label>
                                <input type="text" class="form-control" placeholder="" name="tx_nombres">
                            </div>
                            <div class="form-group">
                                <label>DNI <span class="text-danger">*</span></label>
                                <input type="number" class="form-control" placeholder="" name="nu_dni">
                            </div>
                            <div class="form-group">
                                <label>Direccion <span class="text-danger">*</span></label>
                                <input type="text" class="form-control" placeholder="" name="tx_direccion">
                            </div>
                            <div class="form-group">
                                <label>Fecha Nacimiento <span class="text-danger">*</span></label>
                                <input type="Date" class="form-control" placeholder="" name="dt_fecha_nac">
                            </div>
                            <div class="form-group">
                                <label>Email <span class="text-danger">*</span></label>
                                <input type="email" class="form-control" placeholder="" name="tx_email">
                            </div>
                            <div class="form-group">
                                <label>Contraseña <span class="text-danger">*</span></label>
                                <input type="password" class="form-control" placeholder="" name="tx_contrasena">
                            </div>
                            <div class="form-group">
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" id="customControlAutosizing">
                                    <label class="custom-control-label" for="customControlAutosizing">I agree with all <a href="terms.html">Terms & Conditions</a></label>
                                </div>
                            </div>
                            <input type="submit" class="btn btn-success btn-block" value="Registrar">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Register -->

biblioteca-frontend/biblioteca-frontend/Views/Home/_Catalogo.cshtml
@using biblioteca_frontend.Models
@model List<biblioteca_frontend.Models.Catalogo>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Main Slider With Form -->
<section class="osahan-slider">
    <div class="bg-buscador">
        <form class="buscador-form" action="@Url.Action("Search","Home")">
            <input class="buscador-input" placeholder="   Ingresa el libro a buscar" type="text" name="name">
            <input class="buscador-button" type="submit" value="Buscar">
        </form>
    </div>
</section>
<!-- End Main Slider With Form -->

<!-- Properties List -->
<section class="section-padding">
    <div class="section-title text-center mb-5">
        <h2>Nuestros libros más buscados</h2>
        <p>Da click sobre la imagen para acceder al contenido.</p>
    </div>
    <div class="container">
        @{
            int column = 3;
            int countItems = Model.Count();
            int rows = countItems / column + 1;
            int pos = 0;

            for (int f = 0; f < rows; f++)
            {
                <div class="row">
                    @for (int c = 0; c < column && ((countItems - pos) > 0); c++)
                    {
                        var item = Model.ElementAt(pos);
                        <div class="col-lg-4 col-md-4">
                            <div class="card card-list">
                                <a href="@Url.Action("Details","Catalogo",new {id = item.id_articulo})">
                                    <img class="card-img-top" src="@item.tx_imagen_url" alt="Card image cap" style="height:200px">
                                    <div class="card-body" style="height:90px">
                                        <h5 class="card-title">@item.tx_descripcion</h5>
                                        <h6 class="card-subtitle mb-2 text-muted"><i class="mdi mdi-home-map-marker"></i>@item.tx_cod_bibl</h6>
                                    </div>
                                    <div class="card-footer">
                                        <div><i class="mdi mdi-sofa"></i>Ubicación: <strong>@item.tx_ubicacion1</strong></div>
                                        <div><i class="mdi mdi-scale-bathroom"></i>Ubicación alterna: <strong>@item.tx_ubicacion2</strong></div>
                                        <div><i class="mdi mdi-scale-bathroom"></i>Código de barras: <strong>@item.tx_cod_barras</strong></div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        pos++;
                    }
                </div>
            }

        }
    </div>
</section>
<!-- End Properties List -->